[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agent-runtime-cli"
version = "0.1.0"
description = "Agent Runtime Manager CLI"
requires-python = ">=3.11.4"
dependencies = [
    "click>=8.0.0",
    "python-dotenv>=1.0.0",
    "fastapi>=0.100.0",
    "uvicorn>=0.23.0",
    # local dependencies
    # "openjiuwen-runtime-management @ file:///${PROJECT_ROOT}/../management",
    "openjiuwen-runtime-management==0.0.1",
]

[tool.uv]
default-groups = ['dev']

[dependency-groups]
dev = [
    "ruff==0.9.10",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["*.egg-info", "tests"]
include = ["openjiuwen_runtime*"]

[project.scripts]
openjiuwen = "openjiuwen_runtime.cli.main:cli"
