ARG BASE_IMAGE
ARG IMAGE_VERSION
FROM ${BASE_IMAGE}:${IMAGE_VERSION}

ARG PIP_EXTRA_ARGS="-i https://mirrors.aliyun.com/pypi/simple/"
ARG NPM_REGISTRY=https://registry.npmmirror.com
ARG VITE_PRODUCT_NAME=JiuwenSwarm
ENV VITE_PRODUCT_NAME=${VITE_PRODUCT_NAME}

RUN uv pip install --system -e "./applications/manager/manager_server" \
    ${PIP_EXTRA_ARGS}

USER app
WORKDIR /app/agent-runtime/applications/manager/manager_web
ENV NPM_CONFIG_REGISTRY=${NPM_REGISTRY}
RUN npm install
RUN npm run build

WORKDIR /app/agent-runtime
ENV PATH=$PATH:/home/app/.local/bin
ENV MANAGER_WEB_HOST=0.0.0.0

EXPOSE 5273
CMD ["manager-web"]
